// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using loja1.Data;

#nullable disable

namespace loja1.Migrations
{
    [DbContext(typeof(lojaDbContext))]
    [Migration("20231012042034_parte2")]
    partial class parte2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Produtocarrinho", b =>
                {
                    b.Property<int>("ProdutosProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("carrinhoId")
                        .HasColumnType("int");

                    b.HasKey("ProdutosProdutoId", "carrinhoId");

                    b.HasIndex("carrinhoId");

                    b.ToTable("Produtocarrinho");
                });

            modelBuilder.Entity("loja1.Models.Agranel", b =>
                {
                    b.Property<int>("AgranelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Peso")
                        .HasColumnType("double");

                    b.Property<double>("Preco_Peso")
                        .HasColumnType("double");

                    b.HasKey("AgranelId");

                    b.ToTable("Agraneis");
                });

            modelBuilder.Entity("loja1.Models.Aluguel", b =>
                {
                    b.Property<int>("AluguelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Dias_Alugado")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Preco_Dia")
                        .HasColumnType("double");

                    b.HasKey("AluguelId");

                    b.ToTable("Alugueis");
                });

            modelBuilder.Entity("loja1.Models.Carro", b =>
                {
                    b.Property<int>("CarroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ano")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Preco")
                        .HasColumnType("double");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CarroId");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("loja1.Models.Perecivel", b =>
                {
                    b.Property<int>("PereciveisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DataFabricação")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DataValidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<double>("preco")
                        .HasColumnType("double");

                    b.HasKey("PereciveisId");

                    b.ToTable("Pereciveis");
                });

            modelBuilder.Entity("loja1.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Preco")
                        .HasColumnType("double");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("ProdutoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("loja1.Models.Remedio", b =>
                {
                    b.Property<int>("RemedioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Preco")
                        .HasColumnType("double");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<bool>("Receita")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("RemedioId");

                    b.ToTable("Remedios");
                });

            modelBuilder.Entity("loja1.Models.carrinho", b =>
                {
                    b.Property<int>("carrinhoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("loginId")
                        .HasColumnType("int");

                    b.Property<double>("precototal")
                        .HasColumnType("double");

                    b.HasKey("carrinhoId");

                    b.HasIndex("loginId");

                    b.ToTable("carrinhos");
                });

            modelBuilder.Entity("loja1.Models.login", b =>
                {
                    b.Property<int>("loginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Usarname")
                        .HasColumnType("longtext");

                    b.HasKey("loginId");

                    b.ToTable("logins");
                });

            modelBuilder.Entity("Produtocarrinho", b =>
                {
                    b.HasOne("loja1.Models.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutosProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("loja1.Models.carrinho", null)
                        .WithMany()
                        .HasForeignKey("carrinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("loja1.Models.carrinho", b =>
                {
                    b.HasOne("loja1.Models.login", "login")
                        .WithMany()
                        .HasForeignKey("loginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("login");
                });
#pragma warning restore 612, 618
        }
    }
}
